### ISSUE TITLE
Does not remove anchor/link text when image is also a link

### ISSUE THREAD

**Issue by Daeraxa** [mak2002/joplin-remove-images-from-note#1]
There is a small issue with the way this handles hyperlinked images as taken by the webclipper.
For example clip: https://en.wikipedia.org/wiki/Human_head
Some image links are shown within hyperlinks e.g. `[![Proportions of the Head.jpg](:/b8ce842087404b30a91c4892cc97e805)](https://en.wikipedia.org/wiki/File:Proportions_of_the_Head.jpg)`

Running your plugin results in a weird empty link that isn't rendered (as it has no text) i.e.
`[](https://en.wikipedia.org/wiki/File:Proportions_of_the_Head.jpg)` as it is only reading the image tag part.
So I guess it should either be taking the entire string out or it should be replacing the now empty `[]` section with the contents of the resource section.

**Comment by mak2002** [comment]
I will work on this and fix it soon.

**Comment by mak2002** [comment]
hey @Daeraxa , I have fixed this in latest version. Can you please confirm this on your side so that this issue can be closed?

**Comment by Daeraxa** [comment]
Looks good to me, it removes what I expected from the test note I used 👍
